
# Site settings
title:       Loop's Blog
email:       'nishantjo.12@gmail.com'
description: 'Blog for understanding, with different outlook'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         '' # The base hostname & protocol for your site
twitter:     'twitter.com/Nishant06394875'
github:      'github.com/nishantjoshi00'
instagram:   'instagram.com/nishantjosh'
facebook:    ''

markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
